---
title: "rent21"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align='center',
    fig.pos='H',
    fig.path = "plots/",
    dev = c("png"),
    dpi=200
)
```

## R Markdown



```{r, message=F,include=F}
library(stargazer)#stargazer
library(dplyr) #filter
library(ggplot2)
library(corrplot) # Correlation plot [corrplot()]
library("RColorBrewer")#brewer.pal
library(knitr)
library(xtable)
```

## Including Plots


```{r, warning=F,fig.height=5 , fig.width=10}

importData=read.csv("pop-inc-rent-rc-if-allyear-cleaner-correct.CSV",stringsAsFactors=F, na.strings=c(NA,"NA"," NA"))  #read data
data <- importData[complete.cases(importData[c("MedianRent","MedianHouseholdIncome","TotalPopulation")]),] #omit NA

```

```{r, warning=F,fig.height=5 , fig.width=10}
# data type
data$Geography<-as.factor(data$Geography)
data$MedianRent<-as.numeric(data$MedianRent)
data$MedianHouseholdIncome<-as.numeric(data$MedianHouseholdIncome)
data$TotalPopulation<-as.numeric(data$TotalPopulation)
data$InflationRates<-as.numeric(data$InflationRates)
data$Year<-as.factor(data$Year)
data$RentControl<-as.factor(data$RentControl)

```

```{r, warning=F,fig.height=5 , fig.width=10}
#city data only
data_city = filter(data, Geography !=c('California'))
data_city = filter(data_city, !grepl('.*County', Geography))
#total ca data only 
data_ca = filter(data, Geography == 'California')
```


```{r, warning=F,fig.height=5 , fig.width=10}
#data exploration 

#Histogram of CA Cities' Median Rent
ggplot(data_city, aes(x=MedianRent)) + 
  geom_histogram(color="#e9ecef")+
  ggtitle("Histogram of Median Rent") +
  xlab("Median Rent") + ylab("Dallors")
#Histogram of CA Cities' Median Household Income
ggplot(data_city, aes(x=MedianHouseholdIncome)) + 
  geom_histogram(color="#e9ecef")+
  ggtitle("Histogram of Median Household Income") +
  xlab("Median Household Income") + ylab("Dallors")

#Pie Chart of Rent Control

label1<-paste(c("1: Rent Control&Just Cause","2: Weakened Rent Control&Just Cause","3: Rent Control/Just Cause","4. No Rent Control"),round(100*table(data_city$RentControl)/1369),"%",sep=" ")
pie(table(data_city$RentControl),label=label1,col = brewer.pal(n = 4, name = "RdBu"),main="Pie Chart of Rent Control")

```
```{r, warning=F,fig.height=5 , fig.width=10}
#Pearson correlation
kable(cor(data_city[2:5],),caption="Pearson correlation Table")
#scatter plot of matrices
my_cols <- brewer.pal(n = 4, name = "RdBu") 
pairs(data_city[2:5],pch = 19, lower.panel = NULL,
      col = my_cols[data_city$RentControl]) 

data_city %>% 
  select(MedianRent, MedianHouseholdIncome, TotalPopulation,InflationRates) %>% 
  cor() %>% 
  corrplot(method = "number",
           type = "upper",
           tl.cex = 0.8,
           tl.srt = 45,
           tl.col = "black")

```

```{r, warning=F,fig.height=5 , fig.width=10}
#Annual rent
data_ca$MedianYearRent<-data_ca$MedianRent*12

#ca's Median Rent and Median Household Income changes
ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianYearRent), ) + 
  geom_line(aes(y=MedianYearRent,group = 1 , color="Median Rent")) +
  geom_point(aes(y=MedianHouseholdIncome)) + 
  geom_line(aes(y=MedianHouseholdIncome,group = 1 , color="Median Household Income"))+
  ggtitle("CA's Median Rent and Median Household Income In 2010-2019") +
  xlab("Year") + ylab("Dallors")

#ca's Median Rent and Median Household Income Increasing Rate changes
ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianHouseholdIncomeIncreasingRate), ) + 
  geom_line(aes(y=MedianHouseholdIncomeIncreasingRate,group = 1 , color="Median Household Income Increasing Rate ")) +
  geom_point(aes(y=MedianRentIncreasingRate)) + 
  geom_line(aes(y=MedianRentIncreasingRate,group = 1 , color="Median Rent Increasing Rate"))+
  ggtitle("CA's Median Rent and Median Household Income Increasing Rate In 2010-2019") +
  xlab("Year") + ylab("Rate")

#ca's Median Rent and Median Household Income Increasing Value
data_ca$MedianYearRentS<-data_ca$MedianYearRent-data_ca$MedianYearRent[1]
data_ca$MedianHouseholdIncomeS<-data_ca$MedianHouseholdIncome-data_ca$MedianHouseholdIncome[1]
ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianYearRentS), ) + 
  geom_line(aes(y=MedianYearRentS,group = 1 , color="Median Rent")) +
  geom_point(aes(y=MedianHouseholdIncomeS)) + 
  geom_line(aes(y=MedianHouseholdIncomeS,group = 1 , color="Median Household Income"))+
  ggtitle("CA's Median Rent and Median Household Income Increasing Value In 2010-2019") +
  xlab("Year") + ylab("Dallors")

#ca's Rent v.s. Income Rate change
data_ca$RentIncomeRate<-data_ca$MedianYearRent/data_ca$MedianHouseholdIncome
ggplot(data_ca, aes(x = Year, y = RentIncomeRate,group = 1 , color="Rent v.s. Income Rate")) +
  geom_line(color="blue")+
  ggtitle("CA's Rent v.s. Income Rate changes In 2010-2019") +
  xlab("Year") + ylab("Rate")

```

```{r, warning=F,fig.height=5 , fig.width=10}
#renlationship between RentControl and MedianRent

ggplot(data_city, aes(x = RentControl, y = MedianRent)) +
  geom_boxplot()+
  ggtitle("Median Rent v.s. Rent Control") +
  xlab("Rent Control level") + ylab("Median Rent(dollars)")

#renlationship between RentControl and MedianRentIncreasingRate
ggplot(data_city, aes(x = RentControl, y = MedianRentIncreasingRate)) +
  geom_boxplot()+
  ggtitle("MedianRent Increasing Rate v.s. Rent Control") +
  xlab("Rent Control level") + ylab("MedianRent Increasing Rate(dollars)")

#renlationship between RentControl and MedianHouseholdIncome

ggplot(data_city, aes(x = RentControl, y = MedianHouseholdIncome)) +
  geom_boxplot()+
  ggtitle("Median Household Income v.s. Rent Control") +
  xlab("Rent Control level") + ylab("Median Household Income(dollars)")


```



```{r, warning=F,fig.height=5 , fig.width=10}
#the trainning model of MedianRent Increasing Rate
fit_r=lm(MedianRentIncreasingRate~MedianHouseholdIncomeIncreasingRate +InflationRates +Year+ RentControl+TotalPopulation,data=data_city)

summary(fit_r)

kable(xtable(fit_r))



```

