---
title: "rent21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r, message=F,include=F}

library(dplyr) #filter
library(ggplot2)
library(corrplot) # Correlation plot [corrplot()]

```

## Including Plots


```{r, message=F,include=F}

importData=read.csv("pop-inc-rent-rc-if-allyear-cleaner-correct.CSV",stringsAsFactors=F, na.strings=c(NA,"NA"," NA"))  #read data
data <- importData[complete.cases(importData[c("MedianRent","MedianHouseholdIncome","TotalPopulation")]),] #omit NA

```

```{r pressure, echo=FALSE}
# data type
data$Geography<-as.factor(data$Geography)
data$MedianRent<-as.numeric(data$MedianRent)
data$MedianHouseholdIncome<-as.numeric(data$MedianHouseholdIncome)
data$TotalPopulation<-as.numeric(data$TotalPopulation)
data$InflationRates<-as.numeric(data$InflationRates)
data$Year<-as.factor(data$Year)
data$RentControl<-as.factor(data$RentControl)

```

```{r pressure, echo=FALSE}
#city data only
data_city = filter(data, Geography !=c('California'))
data_city = filter(data_city, !grepl('.*County', Geography))
#total ca data only 
data_ca = filter(data, Geography == 'California')
```


```{r pressure, echo=FALSE}
#data exploration 
hist(data_city$MedianRent,50,main="Histogram of Median Rent", xlab="Median Rent") #Histogram of CA Cities' Median Rent
hist(data_city$MedianHouseholdIncome,50,main="Histogram of Median Household Income", xlab="Income") # Histogram of CA Cities' Median Household Income

#Pie Chart of Rent Control
label1<-paste(c("1: Rent Control&Just Cause","2: Weakened Rent Control&Just Cause","3: Rent Control/Just Cause","4. No Rent Control"),round(100*table(data_city$RentControl)/1369),"%",sep=" ")
pie(table(data_city$RentControl),label=label1,main="Pie Chart of Rent Control")

```
```{r pressure, echo=FALSE}
#Pearson correlation
cor(data_city[2:5],)
#scatter plot of matrices
my_cols <- brewer.pal(n = 4, name = "RdBu") 
pairs(data_city[2:5],pch = 19, lower.panel = NULL,
      col = my_cols[data_city$RentControl]) 


data_city %>% 
  select(MedianRent, MedianHouseholdIncome, TotalPopulation,InflationRates) %>% 
  cor() %>% 
  corrplot(method = "number",
           type = "upper",
           tl.cex = 0.8,
           tl.srt = 45,
           tl.col = "black")
```

```{r pressure, echo=FALSE}
#Annual rent
data_ca$MedianYearRent<-data_ca$MedianRent*12
#
ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianYearRent), ) + 
  geom_line(aes(y=MedianYearRent,group = 1 , color="Median Rent")) +
  geom_point(aes(y=MedianHouseholdIncome)) + 
  geom_line(aes(y=MedianHouseholdIncome,group = 1 , color="Median Household Income"))

ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianHouseholdIncomeIncreasingRate), ) + 
  geom_line(aes(y=MedianHouseholdIncomeIncreasingRate,group = 1 , color="Median Household Income Increasing Rate ")) +
  geom_point(aes(y=MedianRentIncreasingRate)) + 
  geom_line(aes(y=MedianRentIncreasingRate,group = 1 , color="Median Rent Increasing Rate"))

data_ca$MedianYearRentS<-data_ca$MedianYearRent-data_ca$MedianYearRent[1]
data_ca$MedianHouseholdIncomeS<-data_ca$MedianHouseholdIncome-data_ca$MedianHouseholdIncome[1]
ggplot(data_ca, aes(x = Year)) +
  geom_point(aes(y=MedianYearRentS), ) + 
  geom_line(aes(y=MedianYearRentS,group = 1 , color="Median Rent")) +
  geom_point(aes(y=MedianHouseholdIncomeS)) + 
  geom_line(aes(y=MedianHouseholdIncomeS,group = 1 , color="Median Household Income"))

data_ca$RentIncomeRate<-data_ca$MedianYearRent/data_ca$MedianHouseholdIncome
ggplot(data_ca, aes(x = Year, y = RentIncomeRate,group = 1 , color="Rent v.s. Income Rate")) +
  geom_line()



```

```{r pressure, echo=FALSE}
data_2019 = filter(data, Year == '2019')

ggplot(data_2019, aes(x = RentControl, y = MedianRent)) +
  geom_boxplot()

ggplot(data_2019, aes(x = RentControl, y = MedianHouseholdIncome)) +
  geom_boxplot()
```


```{r}
model<-lm(MedianRent~MedianHouseholdIncome +InflationRates +Year+ RentControl+TotalPopulation,data=data_city)
summary(model)
modelrate<-lm(MedianRentIncreasingRate~MedianHouseholdIncomeIncreasingRate +InflationRates +Year+ RentControl,data=data_city)
summary(modelrate)
```

